### ISSUE TITLE
Add support for rendering to a virtual DOM in the browser

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#366]
Currently, the Marko compiler compiles a template to a program that, when executed, will render an HTML string to a stream. This is perfect for the server, but it is less than ideal in the browser since the HTML string must be parsed using something like `innerHTML` in order to update the DOM. Instead, we plan to update Marko to support a new "virtual DOM" output mode for the compiler and an accompanying virtual DOM runtime. The templates will continue to be compiled to a program that renders an HTML stream for the server, but templates will be compiled to render to a virtual DOM tree in the browser. Supporting multiple compilation outputs will allow optimizations in the browser that were not possible before.

To make things more clear, let's take a look at an example template:

``` xml
<h1 class="title">
    Hello ${data.name}!
</h1>

<if(data.colors.length)>
    <ul>
        <li for(color in data.colors)>
            ${color}
        </li>
    </ul>
</if>
<else>
    <div class="empty">
        No colors!
    </div>
</else>
```

The current compiled output for the above template is similar to the following:

``` javascript
function render(data, out) {
  out.w("<h1 class=\"title\">Hello " +
    escapeXml(data.name) +
    "!</h1>");

  if (data.colors.length) {
    out.w("<ul>");

    forEach(data.colors, function(color) {
      out.w("<li>" +
        escapeXml(color) +
        "</li>");
    });

    out.w("</ul>");
  } else {
    out.w("<div>No colors!</div>");
  }
}
```

We are planning to go with the following virtual DOM output when compiled for the browser (not exact):

``` javascript
var attrs0 = { class: 'title' };

var el0 = createElement('div', { class: 'empty' }, 1 /* child count */)
    .text('No colors!');

function render(data, out) {
    out.element('h1', attrs0, 1)
        .text('Hello ' + data.name + '!');

    if (data.colors.length) {
        out.beginElement('ul');

        forEach(data.colors, function(color) {
            out.element('li', null, 1)
                .text(color)
        });

        out.endElement();
    } else {
        out.node(el0);
    }
}
```

A few things to note:
- Optimization: static subtrees are pulled into variables that are only initialized once and reused for every render
- Optimization: static attributes that are on dynamic elements are pulled out to static variables
- Optimization: Diffing is skipped when comparing static subtrees
- Async rendering will continue to be supported on both the server and in the browser. Async fragments will begin with a partially constructed virtual DOM subtree
- `out.write()` will not be allowed when rendering to a virtual DOM
- `out.getRootNode()` can be used to get the root [DocumentFragment](https://github.com/marko-js/marko-vdom#documentfragment) node for the virtual DOM tree being rendered.

Tasks:
- [x] Provide a virtual DOM implementation that is compatible with morphdom. Done: [marko-vdom](https://github.com/marko-js/marko-vdom)
- [x] Update [morphdom](https://github.com/patrick-steele-idem/morphdom) to support diffing the real DOM with a compliant virtual DOM. Done: [morphdom PR #83](https://github.com/patrick-steele-idem/morphdom/pull/83)
- [x] Update the Marko compiler to support multiple output modes
- [x] Implement the codegen for the virtual DOM output mode (almost done)
- [x] Optimize using `isSameNode()` for static subtrees
- [x] Update [async-writer](https://github.com/marko-js/async-writer) to support a virtual DOM runtime. Done: [async-vdom-builder](https://github.com/marko-js/async-vdom-builder)
- [x] Merge in [raptor-renderer](https://github.com/raptorjs/raptor-renderer) functionality into [async-vdom-builder](https://github.com/marko-js/async-vdom-builder) and [async-writer](https://github.com/marko-js/async-writer)
- [x] Additional optimizations for static attributes on non-static sub trees
- [ ] Default to `vdom` output for [lasso-marko](https://github.com/lasso-js/lasso-marko)

**Comment by PierBover** [comment]
How would that work with event handlers?

In [`react-templates`](https://github.com/wix/react-templates#event-handlers) for example you can assign events using the same properties React uses.

**Comment by patrick-steele-idem** [comment]
@PierBover Anything is possible because Marko allows for custom compile-time transforms and custom code generators for custom tags and this allows for custom JavaScript to be inserted into the compiled template to attach event listeners or whatever else is needed.

Marko Widgets is an example of a UI components library that utilizes compile-time transforms to supports declarative event bindings for both DOM events and custom widget events. Marko Widgets allows named events to be bound to a named with method. How Marko Widgets handles event binding is a subtle implementation detail, but it allows the browser to pick up right where the server left off and unlike with React, it is not necessary to rerender the UI in the browser if it was already rendered on the server. The reason React requires that the UI be rerendered in the browser is because a reference to a listener function on the server can't be passed down to the browser.

More details: http://markojs.com/blog/a-closer-look-at-marko-widgets/#how-does-event-delegation-work

**Comment by ianvonholt** [comment]
What is the expected performance impact, if there is any at all?

**Comment by patrick-steele-idem** [comment]
@ianvonholt for now we only have raw numbers (no fancy graphs) for a benchmark of the new [marko-vdom](https://github.com/marko-js/marko-vdom) implementation that shows very significant speedups when measuring the time it takes to build a virtual DOM tree compared to a real DOM tree, as well as the time it takes to walk a virtual DOM tree compared to a real DOM tree: https://github.com/marko-js/marko-vdom/blob/master/docs/benchmark-results.md

While a virtual DOM benchmark provides some significant gains, I suspect the bigger improvements will come from the fact that we can now skip rerendering parts of a template that are constant. That is, the improved compiler will separate out a DOM subtree to a virtual DOM node that is only created once and used for every rerender. On top of that, we also mark that virtual DOM node as constant so that also will completely skip diffing entire DOM subtrees that are constant. This was not really possible before when rendering to an HTML string since the entire HTML string was being parsed to produce a real DOM even though many of the HTML strings were constant.
